# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   # docker run -d --name nginx nginx
#   - name: nginx
#     image: nginx
#   - name: nginx
#     image: nginx


apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  containers:
  - name: nginx
    image: nginx
  # - name: almalinux
  #   image: almalinux:9