apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: expense
    component: backend
    environment: dev
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80